language: python
python:
  - "2.7"

sudo: false

addons:
  apt:
    packages:
      # basics
      - linux-headers-3.13.0-40-generic
      - build-essential
      # For building things
      - cmake
      # for python module gmpy2
      - libgmp-dev
      - libmpfr-dev

# Environment setup
before_install:
  # Added Local Environment Update
  - export LOCAL_ROOT=${HOME}/.local
  - export CPATH=${LOCAL_ROOT}/include:${CPATH}
  - export PATH=${LOCAL_ROOT}/bin:$PATH
  - export LD_LIBRARY_PATH=${LOCAL_ROOT}/lib64:${LOCAL_ROOT}/lib:$LD_LIBRARY_PATH
  - mkdir ${LOCAL_ROOT}
  # Setup local conda python
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n smqtk-$TRAVIS_PYTHON_VERSION python=$TRAVIS_PYTHON_VERSION
  - source activate smqtk-$TRAVIS_PYTHON_VERSION
  # Required gmpy2 deps (taken from scipy .travis.yml)
  - export MPC_VERSION=1.0.3
  - wget ftp://ftp.gnu.org/gnu/mpc/mpc-${MPC_VERSION}.tar.gz
  - tar xzf mpc-${MPC_VERSION}.tar.gz
  - pushd mpc-${MPC_VERSION}
  - ./configure --prefix=${LOCAL_ROOT}
  - make
  - make install
  - popd

# "Install" of SMQTK + immediate deps
install:
  - conda install -q --file requirements.conda.txt
  - pip install -qr requirements.pip.txt
  - pip install gmpy2

  # Build components of SMQTK
  - mkdir _build
  - pushd _build
  - cmake .. && make
  - popd

  # Environment var export
  - export PATH=$PWD/_build/TPL/install/bin:$PATH
  - export PYTHONPATH=$PWD/_build/python:$PWD/_build/TPL/install/lib/python2.7/site-packages:$PYTHONPATH

# Run tests here
script:
  - sh ./run_tests.sh
