language: python

jobs:
  include:
    # Linux - Ubuntu Xenial
    - os: linux
      dist: xenial
      python: "2.7"
    - os: linux
      dist: xenial
      python: "3.6"
    - os: linux
      dist: xenial
      python: "3.7"
    # Linux - Ubuntu Bionic
    - os: linux
      dist: bionic
      python: "2.7"
    - os: linux
      dist: bionic
      python: "3.6"
    - os: linux
      dist: bionic
      python: "3.7"

sudo: false

addons:
  apt:
    packages:
      # basics
      - linux-headers-generic
      - build-essential
      # For building things
      - cmake

# "Install" of SMQTK + immediate deps
install:
  # install python dependencies to environment
  - pip install -r requirements.txt
  - PYTHONINSTALLPREFIX="$(realpath "$(dirname "$(which python)")/..")"
  - echo "${PYTHONINSTALLPREFIX}"

  # Build components of SMQTK
  # - Disabling the building of FLANN due to issues with newer versions of
  #   CMake and GCC. If FLANN desired and used in the future more than it
  #   currently is (basically not at all) then we can work to update the
  #   bundled FLANN TPL or require and external FLANN/bindings installation.
  - mkdir _build
  - pushd _build
  - cmake .. -DCMAKE_BUILD_TYPE:STRING=Release
             -DCMAKE_INSTALL_PREFIX:PATH="$PYTHONINSTALLPREFIX"
             -DSMQTK_BUILD_FLANN:BOOL=OFF
  - make -j$(nproc)
  - make install
  - popd

  # Ensure that it looks like SMQTK is installed via pip
  - pip list | grep -i smqtk

# Run tests here
script:
  - python setup.py test
